### ISSUE TITLE
Consider allowing creation of factory method

### ISSUE THREAD

**Issue by aaronjensen** [eventide-project/initializer#6]
Per discussion with @sbellware, consider adding something along the lines of:

```ruby
initializer :foo, :bar, ctor: true
```

or

```
initializer :foo, :bar, factory_method: :build
```

To automatically create a `self.build` method that would delegate to the initializer.

**Comment by sbellware** [comment]
This suggestion has been declined after conference call discussions with @ntl and @aaronjensen
